name: kelvin

services:
  app:
    container_name: kelvin_app
    depends_on:
      - db
      - redis
    profiles: [ prod ]
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: "ghcr.io/mrlvsb/kelvin:${APP_IMAGE_TAG:-latest}" # Interpolation for Deployment Service
    pull_policy: always
    restart: unless-stopped
    environment:
      # Hardcode the DB and Redis hostnames and ports, since they necessarily
      # run inside the same Docker network, as they are defined in this docker-compose.yml file.
      - DATABASE__HOST=db
      - DATABASE__PORT=5432
      - REDIS__HOST=redis
      - REDIS__PORT=6379
    env_file:
      - .env
    volumes:
      - app_static:/app/static
      - app_socket:/socket
      - ${KELVIN__LOCAL_SETTINGS_PATH}:/app/kelvin/local_settings.py:ro
      - ${UWSGI__CONFIG_PATH}:/app/uwsgi.ini:ro
      - ${KELVIN__TASKS_PATH}:/app/tasks
      - ${KELVIN__SUBMITS_PATH}:/app/submits
      - ${KELVIN__SUBMIT_RESULTS_PATH}:/app/submit_results
  db:
    container_name: kelvin_db
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DATABASE__DB}
      - POSTGRES_USER=${DATABASE__USERNAME}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
    env_file:
      - .env
    volumes:
      - ${DATABASE__DATA_PATH}:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${DATABASE__PORT}:5432"

  redis:
    container_name: kelvin_redis
    image: redis:7
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${REDIS__DATA_PATH}:/data
    ports:
      - "127.0.0.1:${REDIS__PORT}:6379"
    # Save Redis DB to disk at least once per 30 minutes
    # Set maximum DB size to 1 GiB, evict all old keys
    command: "redis-server --save 1800 1 300 100 60 1000 --maxmemory 1024mb --maxmemory-policy allkeys-lru --loglevel warning"

  nginx:
    image: nginx:1.26
    container_name: kelvin_nginx
    depends_on:
      - app
    restart: unless-stopped
    profiles: [ prod ]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX__CONFIG_PATH}:/etc/nginx/nginx.conf:ro
      - ${NGINX__CERTS_PATH}:/etc/nginx/certs:ro
      - ${NGINX__LOGS_PATH}:/var/log/nginx
      - app_static:/app/static:ro
      - app_socket:/socket

  deployment:
    container_name: deployment_app
    profiles: [ prod ]
    build:
      context: deployment_service
      dockerfile: Dockerfile
      target: runtime
    image: "ghcr.io/mrlvsb/deployment:${DEPLOYMENT_IMAGE_TAG:-latest}" # Interpolation for Deployment Service
    pull_policy: always
    restart: unless-stopped
    environment:
      - DOCKER__GHCR_BASE_URL=ghcr.io/mrlvsb
      - DOCKER__COMPOSE_FILE_PATH=/kelvin/docker-compose.yml
    env_file:
      - deployment_service/.env
    volumes:
      - ${REPO__DIRECTORY_PATH}:/kelvin
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  app_static:
  app_socket:
